language: node_js
node_js:
  - "16"
services:
  - docker
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "true" ]; then
    docker run -i --rm -v $(pwd):/app/source -v $(pwd)/.prettierrc:/app/.prettierrc hocptit/eslint-ci:0.0.1 "/app/source/{src,apps,libs,test}/**/*.ts";
    echo "done";
    fi