version: '3.7'
services:
  cqrs-server:
    container_name: cqrs
    image: ghcr.io/hocptit/cqrs:latest
    env_file:
      - .env
    tty: true
    ports:
      - "${PORT}:${PORT}"
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        max-size: "50m"
        loki-basic-auth: "${LOKI_AUTH}"
    networks:
      - cqrs-net

networks:
  cqrs-net:
    external: true