export enum EEnvKey {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  HOST_ADDRESS = 'HOST_ADDRESS',
  SWAGGER_PATH = 'SWAGGER_PATH',
  SWAGGER_IS_PUBLIC = 'SWAGGER_IS_PUBLIC',
  SWAGGER_HOST = 'SWAGGER_HOST',
  SWAGGER_VERSION = 'SWAGGER_VERSION',
  SWAGGER_TITLE = 'SWAGGER_TITLE',
  SWAGGER_DESC = 'SWAGGER_DESC',
  MONGO_URI = 'MONGO_URI',
  LOG_LEVEL = 'LOG_LEVEL',

  SENTRY_DSN = 'SENTRY_DSN',
  SENTRY_DSN_DEBUG = 'SENTRY_DSN_DEBUG',
  SENTRY_DSN_ENABLED = 'SENTRY_DSN_ENABLED',

  GRPC_LEARNING_SERVER_HOST = 'GRPC_LEARNING_SERVER_HOST',
}
