name: deploy develop branch
run-name: ${{ github.actor }} is deploying develop branch
on:
  push:
    branches:
      - 'develop'
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo "Deploy script"
